Repository ansible-collections/cisco.ios, pull requests merged in 2021-12, with the labels that each got.

#465 snmp_server: Resource modules
  README.md
  changelogs/fragments/snmp_server_resource_module.yaml
  docs/cisco.ios.ios_ntp_global_module.rst
  docs/cisco.ios.ios_snmp_server_module.rst
  meta/runtime.yml
  plugins/module_utils/network/ios/argspec/snmp_server/__init__.py
  plugins/module_utils/network/ios/argspec/snmp_server/snmp_server.py
  plugins/module_utils/network/ios/config/snmp_server/__init__.py
  plugins/module_utils/network/ios/config/snmp_server/snmp_server.py
  plugins/module_utils/network/ios/facts/facts.py
  plugins/module_utils/network/ios/facts/snmp_server/__init__.py
  plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
  plugins/module_utils/network/ios/rm_templates/snmp_server.py
  plugins/modules/ios_snmp_server.py
  tests/integration/targets/ios_facts/tests/cli/all_facts.yaml
  tests/integration/targets/ios_snmp_server/defaults/main.yaml
  tests/integration/targets/ios_snmp_server/meta/main.yaml
  tests/integration/targets/ios_snmp_server/tasks/cli.yaml
  tests/integration/targets/ios_snmp_server/tasks/main.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/_parsed.cfg
  tests/integration/targets/ios_snmp_server/tests/cli/_populate_config.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/_remove_config.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/deleted.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/empty_config.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/gathered.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/merged.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/overridden.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/parsed.yaml
  tests/integration/targets/ios_snmp_server/tests/cli/rendered.yaml
  tests/integration/targets/ios_snmp_server/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_snmp_server.py
Labels: gate, snmp_servers

#466 Prep for IOS release v2.6.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/0-copy_ignore_txt.yml
  changelogs/fragments/acl_refactor.yaml
  changelogs/fragments/documentation_update_connection.yaml
  changelogs/fragments/ios_banner_deliminters_and_idempotence.yaml
  changelogs/fragments/l2_interface_issue.yaml
  changelogs/fragments/logging_global_issue.yaml
  changelogs/fragments/ntp_global_fix_false.yml
  changelogs/fragments/sanity-213.yaml
  changelogs/fragments/snmp_server_resource_module.yaml
Labels: gate

#444 Five gigabit ethernet
  changelogs/fragments/fix_fiveGigabit_name.yaml
  plugins/module_utils/network/ios/facts/l2_interfaces/l2_interfaces.py
  plugins/module_utils/network/ios/ios.py
  plugins/module_utils/network/ios/utils/utils.py
  plugins/modules/ios_l2_interface.py
  tests/unit/modules/network/ios/test_ios_l2_interfaces.py
Labels: gate

#472 static_routes unable to render Interfaces in facts properly
  changelogs/fragments/static_route_interface_issue.yaml
  plugins/module_utils/network/ios/config/static_routes/static_routes.py
  plugins/module_utils/network/ios/facts/static_routes/static_routes.py
  tests/unit/modules/network/ios/fixtures/ios_static_routes_config.cfg
  tests/unit/modules/network/ios/test_ios_static_routes.py
Labels: gate, static_routes

#473 ios_acls - unable to render range commands under protocol_options and fragment type changed
  changelogs/fragments/acls_bugfix_and_option_deprication.yaml
  docs/cisco.ios.ios_acls_module.rst
  plugins/module_utils/network/ios/argspec/acls/acls.py
  plugins/module_utils/network/ios/rm_templates/acls.py
  plugins/modules/ios_acls.py
  tests/integration/targets/ios_acls/tests/cli/_parsed.cfg
  tests/integration/targets/ios_acls/tests/cli/parsed.yaml
  tests/integration/targets/ios_acls/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_acls.py
Labels: gate
