Repository ansible-collections/cisco.ios, pull requests merged in 2022-04, with the labels that each got.

#540 [ios_acls] ACLs command ordering and host consideration
  changelogs/fragments/acls_bug_remarks_state.yml
  plugins/module_utils/network/ios/config/acls/acls.py
  plugins/module_utils/network/ios/facts/acls/acls.py
  plugins/module_utils/network/ios/rm_templates/acls.py
  tests/integration/targets/ios_acls/tests/cli/merged.yaml
  tests/integration/targets/ios_acls/tests/cli/overridden.yaml
  tests/integration/targets/ios_acls/tests/cli/rendered.yaml
  tests/integration/targets/ios_acls/tests/cli/replaced.yaml
  tests/integration/targets/ios_acls/tests/cli/rtt.yaml
  tests/integration/targets/ios_acls/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_acls.py
Labels: mergeit, acls

#547 [ios_facts] Line protocol option regex update in legacy facts gathering
  changelogs/fragments/legacy_base_lineprotocol.yml
  plugins/module_utils/network/ios/facts/legacy/base.py
  tests/unit/modules/network/ios/fixtures/ios_facts_show_interfaces
  tests/unit/modules/network/ios/test_ios_facts.py
Labels: mergeit

#549 Prep bugfix release 2.8.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/499-fix-bgp-af-issues.yaml
  changelogs/fragments/acls_bug_remarks_state.yml
  changelogs/fragments/add_symlink_redirects.yml
  changelogs/fragments/fix_sanity_trivial.yml
  changelogs/fragments/legacy_base_lineprotocol.yml
  changelogs/fragments/rename_module_desc.yml
  changelogs/fragments/route_maps_as_numbr.yml
  changelogs/fragments/snmp_server_views_facts.yaml
  docs/cisco.ios.ios_bgp_address_family_module.rst
Labels: mergeit

#546 [logging_global] adds alias for hostname to be replaced with host
  changelogs/fragments/add_alias_to_logging_g_hosts.yml
  docs/cisco.ios.ios_logging_global_module.rst
  plugins/module_utils/network/ios/argspec/logging_global/logging_global.py
  plugins/module_utils/network/ios/config/logging_global/logging_global.py
  plugins/module_utils/network/ios/facts/logging_global/logging_global.py
  plugins/module_utils/network/ios/rm_templates/logging_global.py
  plugins/modules/ios_logging_global.py
  tests/integration/targets/ios_logging_global/tests/cli/overridden.yaml
  tests/integration/targets/ios_logging_global/tests/cli/replaced.yaml
  tests/integration/targets/ios_logging_global/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_logging_global.py
Labels: mergeit, logging_global

#535 [acl_interfaces] facts fixed and optimisation
  changelogs/fragments/acl_interfaces_fix.yml
  docs/cisco.ios.ios_acl_interfaces_module.rst
  plugins/module_utils/network/ios/argspec/acl_interfaces/acl_interfaces.py
  plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py
  plugins/module_utils/network/ios/facts/acl_interfaces/acl_interfaces.py
  plugins/module_utils/network/ios/facts/facts.py
  plugins/module_utils/network/ios/rm_templates/acl_interfaces.py
  plugins/modules/ios_acl_interfaces.py
  tests/integration/targets/ios_acl_interfaces/tests/cli/_parsed.cfg
  tests/integration/targets/ios_acl_interfaces/tests/cli/overridden.yaml
  tests/integration/targets/ios_acl_interfaces/tests/cli/replaced.yaml
  tests/integration/targets/ios_acl_interfaces/tests/cli/rtt.yaml
  tests/integration/targets/ios_acl_interfaces/vars/main.yaml
  tests/unit/modules/network/ios/fixtures/ios_acl_interfaces.cfg
  tests/unit/modules/network/ios/test_ios_acl_interfaces.py
Labels: mergeit, acl_interfaces

#552 Copy ingore txt
  changelogs/fragments/0-ignore.yml
  tests/sanity/ignore-2.14.txt
Labels: mergeit

#548 Fix become raises error when exec prompt timestamp is configured
  changelogs/fragments/fix_become_with_exec_prompt_timestamp.yml
  plugins/terminal/ios.py
Labels: mergeit

#555 [l3_interfaces] fix config code for proper command ordering
  changelogs/fragments/ordering_commands_l3_interface.yml
  plugins/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/ios/rm_templates/l3_interfaces.py
  tests/unit/modules/network/ios/test_ios_l3_interfaces.py
Labels: mergeit, l3_interfaces

#558 [ios_acls] Fix AttributeError on dictionary check
  changelogs/fragments/acl_proto_options_fix.yml
  plugins/module_utils/network/ios/rm_templates/acls.py
Labels: mergeit

#486 updated references of base plugins to netcommon
  changelogs/fragments/netcommon_ref_update.yaml
  galaxy.yml
  plugins/cliconf/ios.py
  plugins/terminal/ios.py
Labels: mergeit, blocks_release, breaking

#567 Add fqcn to ansible_connection to support stable-2.9
  changelogs/fragments/fix_fqcn_netcommon.yml
  tests/integration/targets/ios_smoke/tasks/cli.yaml
  tests/integration/targets/ios_smoke/tests/cli/caching.yaml
  tests/integration/targets/ios_smoke/tests/cli/misc_tests.yaml
Labels: mergeit

#568 prep major release 3.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/0-ignore.yml
  changelogs/fragments/acl_interfaces_fix.yml
  changelogs/fragments/acl_proto_options_fix.yml
  changelogs/fragments/add_alias_to_logging_g_hosts.yml
  changelogs/fragments/fix_become_with_exec_prompt_timestamp.yml
  changelogs/fragments/fix_fqcn_netcommon.yml
  changelogs/fragments/gather_subset_update.yml
  changelogs/fragments/netcommon_ref_update.yaml
  changelogs/fragments/ordering_commands_l3_interface.yml
Labels: mergeit
