Repository ansible-collections/cisco.ios, pull requests merged in 2023-09, with the labels that each got.

#911 ios_service - Bug with private-config-encryption
  changelogs/fragments/bug_ios_service-private_config_encryption.yml
  plugins/module_utils/network/ios/config/service/service.py
  tests/unit/modules/network/ios/test_ios_service.py
Labels: enhancement

#921 [Health check] Fix prefix_lists docs
  changelogs/fragments/fix_prefix_list_docs.yaml
  docs/cisco.ios.ios_prefix_lists_module.rst
  plugins/modules/ios_prefix_lists.py
Labels: enhancement

#900 ios_snmp_server - Enhancement of the `snmp-server user` part
  changelogs/fragments/ios_snmp_user.yml
  plugins/module_utils/network/ios/config/snmp_server/snmp_server.py
  plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
  plugins/module_utils/network/ios/rm_templates/snmp_server.py
  tests/unit/modules/network/ios/test_ios_snmp_server.py
Labels: bug

#930 [acls] update examples and use YAML output for better readibility
  changelogs/fragments/ios_acls.yaml
  docs/cisco.ios.ios_acls_module.rst
  plugins/module_utils/network/ios/facts/acls/acls.py
  plugins/modules/ios_acls.py
Labels: docs

#929 [acls] fixes aces rendering, overridden and replaced state operations.
  .ansible-lint
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  README.md
  changelogs/fragments/ios_acls_fix.yaml
  docs/cisco.ios.ios_command_module.rst
  meta/runtime.yml
  plugins/module_utils/network/ios/config/acls/acls.py
  plugins/module_utils/network/ios/rm_templates/acls.py
  plugins/modules/ios_command.py
  tests/sanity/ignore-2.17.txt
  tests/unit/modules/network/ios/test_ios_acls.py
Labels: bug, docs
