Repository ansible-collections/cisco.ios, pull requests merged in 2023-12, with the labels that each got.

#990 ios_bgp_global - fix template attribute
  changelogs/fragments/template_revoke_bgp.yaml
  docs/cisco.ios.ios_bgp_global_module.rst
  plugins/module_utils/network/ios/config/bgp_global/bgp_global.py
  plugins/module_utils/network/ios/config/vlans/vlans.py
  plugins/module_utils/network/ios/providers/cli/__init__.py
  plugins/module_utils/network/ios/providers/cli/config/__init__.py
  plugins/module_utils/network/ios/providers/cli/config/base.py
  plugins/module_utils/network/ios/providers/cli/config/bgp/__init__.py
  plugins/module_utils/network/ios/providers/cli/config/bgp/address_family.py
  plugins/module_utils/network/ios/providers/cli/config/bgp/neighbors.py
  plugins/module_utils/network/ios/providers/cli/config/bgp/process.py
  plugins/module_utils/network/ios/providers/module.py
  plugins/module_utils/network/ios/rm_templates/bgp_global.py
  plugins/modules/ios_bgp_global.py
  test-requirements.txt
  tests/unit/modules/network/ios/test_ios_bgp_global.py
Labels: bug

#970 Fixes multiple ios_user bugs
  changelogs/fragments/ios_user_fix.yml
  plugins/modules/ios_user.py
  plugins/terminal/ios.py
  tests/integration/targets/ios_user/tests/cli/basic.yaml
  tests/unit/modules/network/ios/test_ios_user.py
Labels: bug, ios_user

#987 ios_bgp_global - added 'bgp.default.ipv4_unicast' and 'bgp.default.route_target.filter'
  changelogs/fragments/fix_ios_bgp_global_20231204173037.yaml
  docs/cisco.ios.ios_bgp_global_module.rst
  plugins/module_utils/network/ios/argspec/bgp_global/bgp_global.py
  plugins/module_utils/network/ios/config/bgp_global/bgp_global.py
  plugins/module_utils/network/ios/facts/bgp_global/bgp_global.py
  plugins/module_utils/network/ios/rm_templates/bgp_global.py
  plugins/modules/ios_bgp_global.py
  tests/integration/targets/ios_bgp_global/tests/cli/merged.yaml
  tests/integration/targets/ios_bgp_global/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_bgp_global.py
Labels: enhancement

#992 ios_facts test verify sub-interface index > 999
  changelogs/fragments/ios_facts_tests.yml
  tests/unit/modules/network/ios/fixtures/ios_facts_show_interfaces
  tests/unit/modules/network/ios/test_ios_facts.py
Labels: enhancement, ios_facts

#994 Fix #993 - user and group IPv6 ACLs
  changelogs/fragments/snmp_server_ipv6_acl.yml
  plugins/module_utils/network/ios/rm_templates/snmp_server.py
  tests/unit/modules/network/ios/test_ios_snmp_server.py
Labels: bug
