Repository ansible-collections/cisco.ios, pull requests merged in 2023-11, with the labels that each got.

#958 fix lint - checkout before action
  .github/workflows/lint.yml
Labels: skip-changelog

#897 Add ios_evpn_evi resource module
  README.md
  changelogs/fragments/add_ios_evpn_evi.yaml
  docs/cisco.ios.ios_evpn_evi_module.rst
  meta/runtime.yml
  plugins/module_utils/network/ios/argspec/evpn_evi/__init__.py
  plugins/module_utils/network/ios/argspec/evpn_evi/evpn_evi.py
  plugins/module_utils/network/ios/config/evpn_evi/__init__.py
  plugins/module_utils/network/ios/config/evpn_evi/evpn_evi.py
  plugins/module_utils/network/ios/facts/evpn_evi/__init__.py
  plugins/module_utils/network/ios/facts/evpn_evi/evpn_evi.py
  plugins/module_utils/network/ios/facts/facts.py
  plugins/module_utils/network/ios/rm_templates/evpn_evi.py
  plugins/modules/ios_evpn_evi.py
  tests/integration/targets/ios_evpn_evi/defaults/main.yaml
  tests/integration/targets/ios_evpn_evi/meta/main.yaml
  tests/integration/targets/ios_evpn_evi/tasks/cli.yaml
  tests/integration/targets/ios_evpn_evi/tasks/main.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/_parsed.cfg
  tests/integration/targets/ios_evpn_evi/tests/cli/_populate_config.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/_remove_config.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/deleted.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/empty_config.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/gathered.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/merged.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/overridden.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/parsed.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/rendered.yaml
  tests/integration/targets/ios_evpn_evi/tests/cli/replaced.yaml
  tests/integration/targets/ios_evpn_evi/vars/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/modules/network/ios/test_ios_evpn_evi.py
Labels: feature, enhancement

#902 Add ios_vxlan_vtep resource module
  README.md
  changelogs/fragments/add_ios_vxlan_vtep.yaml
  docs/cisco.ios.ios_vxlan_vtep_module.rst
  meta/runtime.yml
  plugins/module_utils/network/ios/argspec/vxlan_vtep/__init__.py
  plugins/module_utils/network/ios/argspec/vxlan_vtep/vxlan_vtep.py
  plugins/module_utils/network/ios/config/vxlan_vtep/__init__.py
  plugins/module_utils/network/ios/config/vxlan_vtep/vxlan_vtep.py
  plugins/module_utils/network/ios/facts/facts.py
  plugins/module_utils/network/ios/facts/vxlan_vtep/__init__.py
  plugins/module_utils/network/ios/facts/vxlan_vtep/vxlan_vtep.py
  plugins/module_utils/network/ios/rm_templates/vxlan_vtep.py
  plugins/modules/ios_vxlan_vtep.py
  tests/integration/targets/ios_vxlan_vtep/defaults/main.yaml
  tests/integration/targets/ios_vxlan_vtep/meta/main.yaml
  tests/integration/targets/ios_vxlan_vtep/tasks/cli.yaml
  tests/integration/targets/ios_vxlan_vtep/tasks/main.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/_parsed.cfg
  tests/integration/targets/ios_vxlan_vtep/tests/cli/_populate_config.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/_populate_vlan_vrf_config.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/_remove_config.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/deleted.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/empty_config.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/gathered.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/merged.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/overridden.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/parsed.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/rendered.yaml
  tests/integration/targets/ios_vxlan_vtep/tests/cli/replaced.yaml
  tests/integration/targets/ios_vxlan_vtep/vars/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/modules/network/ios/test_ios_vxlan_vtep.py
Labels: feature

#917 Added 'vlan config' CLI features to exiting ios_vlans plugin.
  changelogs/fragments/fix_ios_vlans.yaml
  docs/cisco.ios.ios_vlans_module.rst
  plugins/module_utils/network/ios/argspec/vlans/vlans.py
  plugins/module_utils/network/ios/config/vlans/vlans.py
  plugins/module_utils/network/ios/facts/vlans/vlans.py
  plugins/module_utils/network/ios/utils/utils.py
  plugins/modules/ios_vlans.py
  tests/integration/targets/ios_vlans/tests/cli/_parsed_vlan_config.cfg
  tests/integration/targets/ios_vlans/tests/cli/_populate_config_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/_remove_config_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/deleted_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/gathered_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/merged_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/overridden_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/parsed_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/rendered_vlan_config.yaml
  tests/integration/targets/ios_vlans/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_vlans.py
Labels: bug

#912 Updated module: Added mdt parameters
  changelogs/fragments/fix_ios_vrf.yaml
  docs/cisco.ios.ios_vrf_module.rst
  plugins/modules/ios_vrf.py
  tests/unit/modules/network/ios/test_ios_vrf.py
Labels: bug

#899 Updated module: added advertise key and fixed inherit peer-policy CLI
  changelogs/fragments/fix_ios_bgp_address_family.yaml
  docs/cisco.ios.ios_bgp_address_family_module.rst
  plugins/module_utils/network/ios/argspec/bgp_address_family/bgp_address_family.py
  plugins/module_utils/network/ios/config/bgp_address_family/bgp_address_family.py
  plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
  plugins/modules/ios_bgp_address_family.py
  tests/integration/targets/ios_bgp_address_family/tests/cli/_populate_config.yaml
  tests/integration/targets/ios_bgp_address_family/tests/cli/merged.yaml
  tests/integration/targets/ios_bgp_address_family/vars/main.yaml
Labels: bug, feature

#976 prep release 5.3.0
  .github/workflows/tests.yml
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/add_ios_evpn_evi.yaml
  changelogs/fragments/add_ios_evpn_global.yaml
  changelogs/fragments/add_ios_vxlan_vtep.yaml
  changelogs/fragments/bgp_global_evpn_fix.yml
  changelogs/fragments/bgp_global_evpn_fix_2.yml
  changelogs/fragments/fix_ios_bgp_address_family.yaml
  changelogs/fragments/fix_ios_evpn_evi.yaml
  changelogs/fragments/fix_ios_vlans.yaml
  changelogs/fragments/fix_ios_vrf.yaml
  changelogs/fragments/ios_ping_fix.yml
  galaxy.yml
Labels: skip-changelog

#979 pending PRs prep release 5.3.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/fix_ios_vlan_config.yaml
Labels: skip-changelog

#983 ios_acls - make sequence optional for rendering of standard acls.
  changelogs/fragments/fix_acls_old.yml
  plugins/module_utils/network/ios/rm_templates/acls.py
Labels: bug

#984 5.3.0 release prep
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/fix_acls_old.yml
Labels: skip-changelog

#981 [major] Prep release 6.0.0
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  docs/cisco.ios.ios_bgp_module.rst
  galaxy.yml
  meta/runtime.yml
  plugins/modules/ios_bgp.py
  tests/config.yml
  tests/integration/targets/ios_bgp/defaults/main.yaml
  tests/integration/targets/ios_bgp/meta/main.yaml
  tests/integration/targets/ios_bgp/tasks/cli.yaml
  tests/integration/targets/ios_bgp/tasks/main.yaml
  tests/integration/targets/ios_bgp/tests/cli/basic.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/modules/network/ios/test_ios_bgp.py
Labels: skip-changelog
