Repository ansible-collections/cisco.ios, pull requests merged in 2023-08, with the labels that each got.

#898 disable auto changelog PR on merge
  .github/workflows/push.yml
  tests/unit/plugins/cliconf/test_ios.py
Labels: skip-changelog

#894 bug: Fixe an error with the pep8 sanity check
  changelogs/fragments/pep8_bugfix.yml
  plugins/module_utils/network/ios/config/ping/ping.py
  plugins/module_utils/network/ios/facts/logging_global/logging_global.py
  plugins/module_utils/network/ios/utils/utils.py
  tests/unit/mock/loader.py
Labels: enhancement

#857 OSPFv2 Enhancement
  changelogs/fragments/rework_ospfv2.yml
  docs/cisco.ios.ios_ospfv2_module.rst
  plugins/module_utils/network/ios/config/ospfv2/ospfv2.py
  plugins/module_utils/network/ios/facts/ospfv2/ospfv2.py
  plugins/module_utils/network/ios/rm_templates/ospfv2.py
  plugins/modules/ios_ospfv2.py
  tests/integration/targets/ios_ospfv2/tests/cli/_initial_vrf_setup.yaml
  tests/integration/targets/ios_ospfv2/tests/cli/_parsed.cfg
  tests/integration/targets/ios_ospfv2/tests/cli/merged.yaml
  tests/integration/targets/ios_ospfv2/tests/cli/overridden.yaml
  tests/integration/targets/ios_ospfv2/tests/cli/replaced.yaml
  tests/integration/targets/ios_ospfv2/tests/cli/rtt.yaml
  tests/integration/targets/ios_ospfv2/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_ospfv2.py
Labels: refactoring

#901 Codecov Workflow update
  changelogs/fragments/codecov_pr.yml
  codecov.yml
Labels: refactoring

#905 update all_green check
  .github/workflows/tests.yml
Labels: bug, skip-changelog

#893 Re-work stderr regex to ensure presence of %
  changelogs/fragments/stderr_re_fix.yaml
  plugins/terminal/ios.py
Labels: bug

#908 Update OSPF examples(Health Check Documenation Activity)
  changelogs/fragments/update_ospf_docs.yaml
  docs/cisco.ios.ios_bgp_global_module.rst
  docs/cisco.ios.ios_ospf_interfaces_module.rst
  docs/cisco.ios.ios_ospfv2_module.rst
  docs/cisco.ios.ios_ospfv3_module.rst
  plugins/modules/ios_bgp_global.py
  plugins/modules/ios_ospf_interfaces.py
  plugins/modules/ios_ospfv2.py
  plugins/modules/ios_ospfv3.py
Labels: documentation, enhancement

#916 [prefix_lists] fix delete state and optimise code
  changelogs/fragments/prefix_list_fix.yaml
  docs/cisco.ios.ios_prefix_lists_module.rst
  plugins/module_utils/network/ios/config/prefix_lists/prefix_lists.py
  plugins/module_utils/network/ios/facts/prefix_lists/prefix_lists.py
  plugins/module_utils/network/ios/rm_templates/prefix_lists.py
  plugins/modules/ios_prefix_lists.py
  tests/integration/targets/ios_command/tests/cli/error_regex.yaml
  tests/integration/targets/ios_prefix_lists/tests/cli/overridden.yaml
  tests/integration/targets/ios_prefix_lists/tests/cli/replaced.yaml
  tests/integration/targets/ios_prefix_lists/vars/main.yaml
Labels: bug

#919 Fixed Issues with setting filter_list , as_path_acl on bgp_address_fa…
  changelogs/fragments/bgp_address_family_bug.yml
  plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
Labels: bug, bgp_address_family
