Repository ansible-collections/cisco.ios, pull requests merged in 2024-01, with the labels that each got.

#991 Added keys to L3 interface plugin
  changelogs/fragments/fix_ios_l3_interfacel_20231207172506.yaml
  docs/cisco.ios.ios_l3_interfaces_module.rst
  plugins/module_utils/network/ios/argspec/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/ios/facts/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/ios/rm_templates/l3_interfaces.py
  plugins/modules/ios_l3_interfaces.py
  tests/integration/targets/ios_l3_interfaces/tests/cli/merged.yaml
  tests/integration/targets/ios_l3_interfaces/vars/main.yaml
  tests/unit/modules/network/ios/test_ios_l3_interfaces.py
Labels: enhancement

#1004 [ios_l3_interfaces] Remove strict ipv6 validation
  changelogs/fragments/ios_l3_ipv6.yml
  plugins/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/ios/utils/utils.py
  tests/unit/modules/network/ios/test_ios_l3_interfaces.py
Labels: bug

#1005 [ios_vlans] remove extra configuration attribute
  changelogs/fragments/ios_vlans_revert.yml
  docs/cisco.ios.ios_bgp_address_family_module.rst
  docs/cisco.ios.ios_bgp_global_module.rst
  docs/cisco.ios.ios_evpn_evi_module.rst
  docs/cisco.ios.ios_evpn_global_module.rst
  docs/cisco.ios.ios_vlans_module.rst
  docs/cisco.ios.ios_vxlan_vtep_module.rst
  plugins/module_utils/network/ios/argspec/vlans/vlans.py
  plugins/module_utils/network/ios/config/vlans/vlans.py
  plugins/module_utils/network/ios/facts/facts.py
  plugins/module_utils/network/ios/facts/vlans/vlans.py
  plugins/module_utils/network/ios/rm_templates/vlans.py
  plugins/modules/ios_bgp_address_family.py
  plugins/modules/ios_bgp_global.py
  plugins/modules/ios_evpn_evi.py
  plugins/modules/ios_evpn_global.py
  plugins/modules/ios_vlans.py
  plugins/modules/ios_vxlan_vtep.py
  test-requirements.txt
  tests/integration/targets/ios_vlans/tests/cli/_populate_config_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/_remove_config_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/deleted_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/gathered_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/merged_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/overridden_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/parsed_vlan_config.yaml
  tests/integration/targets/ios_vlans/tests/cli/rendered_vlan_config.yaml
  tests/unit/modules/network/ios/test_ios_vlans.py
Labels: bug, vlans

#1010 Release 6.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/fix_ios_bgp_global_20231204173037.yaml
  changelogs/fragments/fix_ios_l3_interfacel_20231207172506.yaml
  changelogs/fragments/ios_facts_tests.yml
  changelogs/fragments/ios_l3_ipv6.yml
  changelogs/fragments/ios_user_fix.yml
  changelogs/fragments/ios_vlans_revert.yml
  changelogs/fragments/snmp_server_ipv6_acl.yml
  changelogs/fragments/template_revoke_bgp.yaml
  galaxy.yml
Labels: skip-changelog

#1011 Fixes module_defaults being incorrectly applied to platform actions
  changelogs/fragments/module_defaults.yaml
  meta/runtime.yml
Labels: bug

#1022 [ios_vlans] fix behaviour of shutdown attribute
  changelogs/fragments/vlan_shutdown_fix.yaml
  plugins/module_utils/network/ios/config/vlans/vlans.py
  plugins/module_utils/network/ios/rm_templates/vlans.py
  tests/unit/modules/network/ios/test_ios_vlans.py
Labels: bug

#1023 Release 6.1.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/module_defaults.yaml
  changelogs/fragments/vlan_shutdown_fix.yaml
  galaxy.yml
Labels: skip-changelog

#989 [GHA] Update reference for GitHub actions
  .ansible-lint
  .github/workflows/check_label.yml
  .github/workflows/codecoverage.yml
  .github/workflows/draft_release.yml
  .github/workflows/lint.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  tests/unit/modules/network/ios/test_ios_acls.py
  tox-ansible.ini
Labels: skip-changelog

#1014 Resolve idempotency issue in SNMP Server user attribute handling
  changelogs/fragments/snmp_idempotancy_fix.yml
  plugins/module_utils/network/ios/config/snmp_server/snmp_server.py
  tests/unit/modules/network/ios/test_ios_snmp_server.py
Labels: bug
